### PR TITLE
Added Contact form

### PR DESCRIPTION
**Pull request by AbelG101**
## Changes
- Added a contact form section.
- Added a form element with:
    - with an email and name input fields.
    - a comment area for messages.
- added a flex box styling for the contact section as well as the form.

### CODE REVIEW

**Review by Div685 — CHANGES_REQUESTED** [review]
# 🟠 Project Invalid! ⚓
Hi, **AbelG101**, I'm Divyesh your reviewer for this PR :man_technologist: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not pass Webhint linter. Please resolve the Linter errors and submit another review. Don't worry, this is also part of the learning process. Keep coding.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by wuletawwonte** [comment]
Hello team
- [ ] I noticed you have extra linter configuration file. Please remove `eslintrc.json` file from your repo. That file is a linter configuration file for javascript.

**Review by isaacpitwa — CHANGES_REQUESTED** [review]
## 🟠 Project Invalid! ⚓
Hi @AbelG101 👋🏽

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
You have submitted a project, that does not pass Webhint linter. Please resolve the Linter errors and submit another review. Don't worry, this is also part of the learning process. Keep coding.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

(Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.)

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by AbelG101** [comment]
Dear reviewers, I have literally spent 10 hours looking for errors in my code and there isn't any. This is beyond any beginners capability I have googled it, and talked with other reviewers (even they couldn't figure it out), so I kindly ask you to check my code and review it based on that.

**Comment by wuletawwonte** [comment]
Hello @AbelG101 
I cloned your repo and I was searching for the problem. I noticed you have got a picture file named `#.png`. That's why your webhint test is not passing. Please rename that file something like `sharp.png`. Then run `npx hint .` to see the remaining few errors. I'm sure you can fix all the errors. I'm sorry but we can't review if the linter test is failing.

**Comment by wuletawwonte** [comment]
### @AbelG101, @samlorlah @juanmanuelbyc 
If you are still facing problems. Please write me in slack. I can spare sometime to help you.

**Pull request merged**
